Fmri prereg
crsh/prereg pull request #11
Opened 2019-07-30 16:04 UTC by LisaSpitzer

I started working on the fMRI template. For this, I edited the yaml file and started working on the template itself. I put the text that I have not edited yet into a comment.

2019-07-31 07:27 UTC, crsh commented
Thanks! Looking forward o see further work on this.

2019-09-28 09:21 UTC, crsh commented
Hi Lisa, thanks for the additional work you put into this? I'm not sure what the status of this PR this. Just so we are on the same page, could you request a review from me as soon as you want feedback or think it's ready for merging?

2019-09-28 09:27 UTC, LisaSpitzer commented
Hi Frederik, I'm still working on the fmri template and slowly adding all elements from the original resource. I will contact you as soon as I finish editing.

2019-10-21 14:38 UTC, LisaSpitzer commented
I finished creating the fmri template and would be happy for my commits to be merged with the main branch. If I should change anything about the template, please contact me.

2019-10-30 08:33 UTC, crsh requested changes
Hi Lisa, thanks for this. In addition to my comments, could you remove the `skeleton.log` and `skeleton.pdf` files?

2019-10-30 08:33 UTC, crsh commented on inst/rmarkdown/templates/fmri_prereg/skeleton/skeleton.Rmd
> +<!-- The goal of this template is to provide sufficient information in preregistration for fMRI data design to increase reproducible reporting practices. Text was adopted from the OSF preregistration
Could you separate the links to these papers either by new lines? Could you also maybe use DOI-Links (e.g., https://doi.org/10.1101/054262)?

2019-10-30 08:33 UTC, crsh commented on inst/rmarkdown/templates/fmri_prereg/skeleton/skeleton.Rmd
> +## Project Title
I think we can get rid of this section, as it is redundant with the title in the YAML front matter.

2019-10-30 08:33 UTC, crsh commented on inst/rmarkdown/templates/fmri_prereg/skeleton/skeleton.Rmd
> +Is your preregistration part of a larger project?
How about we skip this question (remove it from the form) and incorporate it in the comment above (e.g., "If your preregistration is part of a larger project, provide a brief description of the larger study.")?

2019-10-30 08:33 UTC, crsh commented on inst/rmarkdown/templates/fmri_prereg/skeleton/skeleton.Rmd
> +- Population:
Could yout try to make this into a table (using the [pipe table](https://pandoc.org/MANUAL.html#tables) syntax)? Not sure whether the template will handle it quite right, but it may be worth a shot.

2019-10-30 08:33 UTC, crsh commented on inst/rmarkdown/templates/fmri_prereg/skeleton/skeleton.Rmd
> +### Target sample size:
Hmm, should we maybe omit the colons in level 3 headings?

2019-10-30 08:33 UTC, crsh commented on inst/rmarkdown/templates/fmri_prereg/skeleton/skeleton.Rmd
> +To obtain our target sample size, we plan to recruit: Enter your response here.
I think for simplicity I would just go with "Enter your response here"

2019-10-30 08:33 UTC, crsh commented on inst/rmarkdown/templates/fmri_prereg/skeleton/skeleton.Rmd
> +> E.g., If the X questionnaire is missing for more than 10% of participants we will not use it or if X does not show variability in response (either ceiling or floor effects) in which we cannot look
Could you include this in the explanatory comment in line 217?

2019-10-30 08:33 UTC, crsh commented on inst/rmarkdown/templates/fmri_prereg/skeleton/skeleton.Rmd
> +- Manufacturer, field strength <!-- in Tesla -->, model name:
I think all this could be turned into an explanatory comment, no?

2019-10-30 08:33 UTC, crsh commented on inst/rmarkdown/templates/fmri_prereg/skeleton/skeleton.Rmd
> +- *Essential sequence & imaging parameters*
Could this maybe also be a table?

2021-02-04 13:10 UTC, crsh requested changes
This looks great, I only added a few minor comments. Additionally, could you please remove the file `inst/rmarkdown/templates/rr_prereg/skeleton/skeleton.pdf`?

2021-02-04 13:10 UTC, crsh commented on R/fmri_prereg.R
> +#' Knit a PDF document using fmri related questions (based on Jessica Flannery, see: https://osf.io/dvb2e/)
Could you adjust this a little, maybe based on the corresponding `template.yml`? E.g. 

> Knit a PDF document using the fMRI preregistration template suggested by Jessica Flannery (https://osf.io/dvb2e/)

2021-02-04 13:10 UTC, crsh commented on inst/rmarkdown/templates/fmri_prereg/skeleton/skeleton.Rmd
> +-	Registration prior to any human observation of the data
Could you remove the white space here so that it becomes `- Registration prior to any human observation of the data`?

2021-02-05 10:08 UTC, LisaSpitzer commented
Hi @crsh, thanks again for the feedback. I have implemented your comments. A merge conflict occured, can you resolve this?

2021-02-11 15:07 UTC, merged